version: '3.8'
name: "ms-pricing-quote-local-config"
services:
  db:
    image: 'postgres@sha256:a5e89e5f2679863bedef929c4a7ec5d1a2cb3c045f13b47680d86f8701144ed7'
    restart: always
    container_name: "database-ms-pricing-quote"
    expose:
      - "5432"
    ports:
      - "5432:5432"
    env_file:
      - ./database-ms-pricing-quote/.env
    volumes:
      - ./database-ms-pricing-quote/init/init.sql:/docker-entrypoint-initdb.d/init.sql
  pgadmin:
    image: dpage/pgadmin4@sha256:2e3747c48b19a98124fa8c8f0e78857bbf494c2f6ee5d271c72917c37d1b3502
    container_name: "pgadmin-ms-pricing-quote"
    env_file:
      - ./pgadmin-ms-pricing-quote/.env
    expose:
      - "80"
    ports:
      - "80:80"
    depends_on:
      - db
