services:
  database:
    image: postgres
    restart: always
    container_name: "postgres"
    ports:
      - "5500:5500"
    environment:
      POSTGRES_USER: "${POSTGRES_PASSWORD}"
      POSTGRES_PASSWORD: "${POSTGRES_USER}"
      POSTGRES_DATABASE: "pricing"
    volumes:
      - ./init/init.sql:/docker-entrypoint-initdb.d/init.sql
    command: -p 5500



  pgadmin:
    image: dpage/pgadmin4
    container_name: "pgamin"
    environment:
      PGADMIN_DEFAULT_EMAIL: "${PGADMIN_DEFAULT_EMAIL}"
      PGADMIN_DEFAULT_PASSWORD: "${PGADMIN_DEFAULT_PASSWORD}"
    ports:
      - "80:80"
    depends_on:
      - database
